# Site settings
name: Ahn Sangmin
email: tjfl9831@gmail.com
url: https://github.com/sang9831
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: sang9831

twitter:
  username: username
