# Site settings
name: Ahn Sangmin
email: tjfl9831@gmail.com
url: url
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: /portfolio

# social
github:
  username: sang9831

twitter:
  username: username
